using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;

namespace AppCore.Entities
{
    public class BaseEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        
        [BsonDateTimeOptions]
        [BsonElement("createIndexes")]        
        public DateTime DataCreate { get; set; } = DateTime.Now;

        public int __v { get; set; }
        
    }
}
